### ISSUE TITLE
Magic Import doesn't work on moodfabrics.com

### ISSUE THREAD

**Issue by cemtai2** [Zambrella/stash-hub-issues#192]
**Describe the bug**
When attempting to import fabric from moodfabrics.com there is an error that says internal:internal.  I tried a few different fabrics to verify it wasn't just one link.

**To Reproduce**
1.  Select a fabric URL from moodfabrics.com (I used https://www.moodfabrics.com/carolina-herrera-metallic-blue-green-and-black-poppies-polyester-and-nylon-brocade-436696)
2. Click magic import and past URL into the correct field.
3. Hit submit.

**Expected behavior**
The fabric information should be imported from the link.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 121.0.6167.189

**Comment by Zambrella** [comment]
@cemtai2 Thanks for submitting this issue. Will have a look next week :)

**Comment by Zambrella** [comment]
@cemtai2 Would you be able to try again? It works fine for me at the moment. Might have been a temporary issue.
