### ISSUE TITLE
Increase timeout for file/image uploads

### ISSUE THREAD

**Issue by Zambrella** [Zambrella/stash-hub-issues#194]
Some people still get timeouts even if their speeds are reasonable.

**Comment by Deborah8G8** [comment]
Hi, can I please ask when this is planned to be implemented?

**Comment by Zambrella** [comment]
> Hi, can I please ask when this is planned to be implemented?

Next week :)

**Comment by Deborah8G8** [comment]
Yay, thank you! Happy to help test if you need someone experiencing the issue.
