### ISSUE TITLE
Capitalisation after apostrophe

### ISSUE THREAD

**Issue by bethanjt** [Zambrella/stash-hub-issues#210]
**Describe the bug**
In name field, the letter after an apostrophe is capitalised when inputting patterns via magic input. I have observed this with both designer and pattern name.
E.g. Helen'S Closet / Men'S t-shirt 

**To Reproduce**
Use magic input for patterns. Input any pattern containing aapostrophe in the designer or pattern name (e.g. Helen's closet)

**Expected behavior**
Letter after apostrophe should not be capitalised

**Screenshots**
![inbound4484542071383135857](https://github.com/Zambrella/stash-hub-issues/assets/36667842/45ab9ae5-8444-4ddf-9ca8-b1e00f99e3e3)
![inbound1888720548346618369](https://github.com/Zambrella/stash-hub-issues/assets/36667842/c515b7bc-c300-403b-8a8a-e752983cfaf1)

**Desktop (please complete the following information):**
- Browser, Microsoft edge, also observed on android app.

**Additional context**
I imagine it's an issue with auto capitalisation treating an apostrophe the same as a space and thinking the next letter is a new word? But that's just my first guess without knowing the codebase.

**Comment by Zambrella** [comment]
@bethanjt Thanks for this bug report! Will look into what's going on.
